firstTempEmbedding/firstTempEmbedding/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using firstTempEmbedding.Models;

namespace firstTempEmbedding.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly MvctestContext _context;

        public EmployeesController(MvctestContext context)
        {
            _context = context;
        }

        // GET: Employees
        public async Task<IActionResult> Index()
        {
              return _context.Employees != null ? 
                          View(await _context.Employees.ToListAsync()) :
                          Problem("Entity set 'MvctestContext.Employees'  is null.");
        }

        // GET: Employees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Employees == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // GET: Employees/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Empname,Salary,Joining,Designation")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: Employees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Employees == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Empname,Salary,Joining,Designation")] Employee employee)
        {
            if (id != employee.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employee.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Employees == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Employees == null)
            {
                return Problem("Entity set 'MvctestContext.Employees'  is null.");
            }
            var employee = await _context.Employees.FindAsync(id);
            if (employee != null)
            {
                _context.Employees.Remove(employee);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeeExists(int id)
        {
          return (_context.Employees?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

firstTempEmbedding/firstTempEmbedding/Controllers/ServiceController.cs
using firstTempEmbedding.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace firstTempEmbedding.Controllers
{
    public class ServiceController : Controller
    {
        private readonly MvctestContext _context;
        public ServiceController(MvctestContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View(_context.Services.ToList());
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Service serv)
        {
            if (ModelState.IsValid)
            {
                _context.Add(serv);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(serv);

        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var data = _context.Services.Find(id);
            return View(data);
        }

        [HttpPost]
        public IActionResult Edit(int id, Service vs)
        {
            if (ModelState.IsValid)
            {

                _context.Update(vs);
                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }
        //[HttpGet]
        //public IActionResult Delete(int id)
        //{
        //    var data = _context.Services.Find(id);
        //    return View(data);
        //}
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var data = _context.Services.Find(id);
            return View(data);
        }

        [HttpPost]
        public IActionResult Delete(int id, Service vs)
        {
            if (ModelState.IsValid)
            {
                _context.Remove(vs);
                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
            var data = _context.Services.Find(id);
            return View(data);
        }
    }

}

firstTempEmbedding/firstTempEmbedding/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>Pluto - Responsive Bootstrap Admin Panel Templates</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- site icon -->
      <link rel="icon" href="~/images/fevicon.png" type="image/png" />
      <!-- bootstrap css -->
      <link rel="stylesheet" href="~/css/bootstrap.min.css" />
      <!-- site css -->
      <link rel="stylesheet" href="~/style.css" />
      <!-- responsive css -->
      <link rel="stylesheet" href="~/css/responsive.css" />
      <!-- color css -->
      <link rel="stylesheet" href="~/css/colors.css" />
      <!-- select bootstrap -->
      <link rel="stylesheet" href="~/css/bootstrap-select.css" />
      <!-- scrollbar css -->
      <link rel="stylesheet" href="~/css/perfect-scrollbar.css" />
      <!-- custom css -->
      <link rel="stylesheet" href="~/css/custom.css" />
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond./js/1.4.2/respond.min.js"></script>
      <![endif]-->
   </head>
   <body class="dashboard dashboard_1">
    <div class="full_container">
        <div class="inner_container">
            <!-- Sidebar  -->
            <nav id="sidebar">
                <div class="sidebar_blog_1">
                    <div class="sidebar-header">
                        <div class="logo_section">
                            <a href="index.html"><img class="logo_icon img-responsive" src="~/images/logo/logo_icon.png" alt="#" /></a>
                        </div>
                    </div>
                    <div class="sidebar_user_info">
                        <div class="icon_setting"></div>
                        <div class="user_profle_side">
                            <div class="user_img"><img class="img-responsive" src="~/images/layout_img/user_img.jpg" alt="#" /></div>
                            <div class="user_info">
                                <h6>John David</h6>
                                <p><span class="online_animation"></span> Online</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="sidebar_blog_2">
                    <h4>General</h4>
                    <ul class="list-unstyled components">
                        <li class="active">
                            <a href="#employees" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-dashboard yellow_color"></i> <span>Employees</span></a>
                            <ul class="collapse list-unstyled" id="employees">
                                <li>
                                    <a asp-action="Index" asp-controller="Employees"> <span>All Employees</span></a>
                                </li> 
                                <li>
                                    <a asp-action="Create" asp-controller="Employees"> <span>Add new employee</span></a>
                                </li> 
                                
                               
                            </ul>
                        </li>
                        
                        <li>
                            <a href="#services" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-diamond purple_color"></i> <span>Services</span></a>
                            <ul class="collapse list-unstyled" id="services">

                                <li>
                                    <a asp-action="Index" asp-controller="Service"> <span>All Services</span></a>
                                </li>
                                <li>
                                    <a asp-action="Create" asp-controller="Service"> <span>Add new Service</span></a>
                                </li>
                            </ul>
                        </li>
                     
                        <li class="active">
                            <a href="#additional_page" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-clone yellow_color"></i> <span>Account</span></a>
                            <ul class="collapse list-unstyled" id="additional_page">
                                <li>
                                    <a href="profile.html">> <span>Profile</span></a>
                                </li>
                               
                                <li>
                                    <a href="logout.html">> <span>Logout</span></a>
                                </li>
                               
                            </ul>
                        </li>
                       

                    </ul>
                </div>
            </nav>
            <!-- end sidebar -->
            <!-- right content -->
            <div id="content">
                <!-- topbar -->
                <div class="topbar">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <div class="full">
                            <button type="button" id="sidebarCollapse" class="sidebar_toggle"><i class="fa fa-bars"></i></button>
                            <div class="logo_section">
                                <a href="index.html"><img class="img-responsive" src="~/images/logo/logo.png" alt="#" /></a>
                            </div>
                            <div class="right_topbar">
                                <div class="icon_info">
                                    <ul>
                                        <li><a href="#"><i class="fa fa-bell-o"></i><span class="badge">2</span></a></li>
                                        <li><a href="#"><i class="fa fa-question-circle"></i></a></li>
                                        <li><a href="#"><i class="fa fa-envelope-o"></i><span class="badge">3</span></a></li>
                                    </ul>
                                    <ul class="user_profile_dd">
                                        <li>
                                            <a class="dropdown-toggle" data-toggle="dropdown"><img class="img-responsive rounded-circle" src="~/images/layout_img/user_img.jpg" alt="#" /><span class="name_user">John David</span></a>
                                            <div class="dropdown-menu">
                                                <a class="dropdown-item" href="profile.html">My Profile</a>
                                                <a class="dropdown-item" href="settings.html">Settings</a>
                                                <a class="dropdown-item" href="help.html">Help</a>
                                                <a class="dropdown-item" href="#"><span>Log Out</span> <i class="fa fa-sign-out"></i></a>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </nav>
                </div>
                <!-- end topbar -->
            @RenderBody()
                  <!-- footer -->
                  <div class="container-fluid">
                     <div class="footer">
                        <p>Copyright © 2018 Designed by html.design. All rights reserved.<br><br>
                           Distributed By: <a href="https://themewagon.com/">ThemeWagon</a>
                        </p>
                     </div>
                  </div>
               </div>
               <!-- end dashboard inner -->
            </div>
         </div>
         </div>
      </div>
      <!-- jQuery -->
      <script src="~/js/jquery.min.js"></script>
      <script src="~/js/popper.min.js"></script>
      <script src="~/js/bootstrap.min.js"></script>
      <!-- wow animation -->
      <script src="~/js/animate.js"></script>
      <!-- select country -->
      <script src="~/js/bootstrap-select.js"></script>
      <!-- owl carousel -->
      <script src="~/js/owl.carousel.js"></script> 
      <!-- chart js -->
      <script src="~/js/Chart.min.js"></script>
      <script src="~/js/Chart.bundle.min.js"></script>
      <script src="~/js/utils.js"></script>
      <script src="~/js/analyser.js"></script>
      <!-- nice scrollbar -->
      <script src="~/js/perfect-scrollbar.min.js"></script>
      <script>
         var ps = new PerfectScrollbar('#sidebar');
      </script>
      <!-- custom js -->
      <script src="~/js/custom.js"></script>
      <script src="~/js/chart_custom_style1.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
   </body>
</html>

       
   
   